#!/usr/bin/env perl

use strict;
use warnings;
use FindBin qw($RealBin);
use Cwd qw/ getcwd abs_path /;

my $AbsRealBin = Cwd::realpath($RealBin);
my $CCAnalyzer = "$AbsRealBin/gcc-handler";
my $CXXAnalyzer = "$AbsRealBin/g++-handler";

sub RunBuildCommand {
	my $Args = shift;
	push @$Args, "CC=$CCAnalyzer";
	push @$Args, "CXX=$CXXAnalyzer";
	print STDOUT "> @$Args";
	return (system(@$Args) >> 8);
}

my $ExitStatus = RunBuildCommand(\@ARGV);
exit $ExitStatus;

